const Endpoints = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    me: "/auth/me",
  },
  user: {
    changePassword: "/user/password",
    sessions: "/user/sessions",
    session: (id: string) => `/user/sessions/${id}`,
  },
  public: {
    courses: "/public/courses",
    course: (slug: string) => `/public/courses/${slug}`,
    teachers: "/public/teachers",
    teacher: (id: string) => `/public/teachers/${id}`,
    stats: "/public/stats",
  },
  admin: {
    students: "/admin/students",
    student: (id: string) => `/admin/students/${id}`,
    studentAttendance: (id: string) => `/admin/students/${id}/attendance`,
    studentGrades: (id: string) => `/admin/students/${id}/grades`,
    studentPayments: (id: string) => `/admin/students/${id}/payments`,
    courses: "/admin/courses",
    course: (id: string) => `/admin/courses/${id}`,
    teachers: "/admin/teachers",
    teacher: (id: string) => `/admin/teachers/${id}`,
    groups: "/admin/groups",
    group: (id: string) => `/admin/groups/${id}`,
    groupStudents: (id: string) => `/admin/groups/${id}/students`,
    schedule: "/admin/schedule",
    lesson: (id: string) => `/admin/schedule/lessons/${id}`,
    lessons: "/admin/schedule/lessons",
    assignments: "/admin/assignments",
    assignment: (id: string) => `/admin/assignments/${id}`,
    assignmentGrades: (id: string) => `/admin/assignments/${id}/grades`,
    exams: "/admin/exams",
    exam: (id: string) => `/admin/exams/${id}`,
    examGrades: (id: string) => `/admin/exams/${id}/grades`,
    attendance: "/admin/attendance",
    payments: "/admin/payments",
    payment: (id: string) => `/admin/payments/${id}`,
    paymentStatus: (id: string) => `/admin/payments/${id}/status`,
    paymentRefund: (id: string) => `/admin/payments/${id}/refund`,
    paymentReceipt: (id: string) => `/admin/payments/${id}/receipt`,
    finance: {
      kpis: "/admin/finance/kpis",
      revenueVsExpense: "/admin/finance/revenue-vs-expense",
      expenseCategories: "/admin/finance/expense-categories",
      categories: "/admin/finance/categories",
      expenses: "/admin/finance/expenses",
      expense: (id: string) => `/admin/finance/expenses/${id}`,
    },
  },
};
export default Endpoints;
