const Endpoints = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    me: "/auth/me",
  },
  user: {
    changePassword: "/user/password",
    sessions: "/user/sessions",
    session: (id: string) => `/user/sessions/${id}`,
  },
  public: {
    stats: "/public/stats",
    testimonials: "/public/testimonials",
    courses: "/public/courses",
    course: (slug: string) => `/public/courses/${slug}`,
    instructors: "/public/instructors",
    instructor: (id: string) => `/public/instructors/${id}`,
    blog: "/public/blog",
    blogCategories: "/public/blog/categories",
    blogPost: (slug: string) => `/public/blog/${slug}`,
    blogComment: (slug: string) => `/public/blog/${slug}/comments`,
    contact: "/public/contact",
  },
  student: {
    enrollments: "/student/enrollments",
    enrollment: (courseId: string) => `/student/enrollments/${courseId}`,
    checkout: "/student/enrollments/checkout",
    lessonProgress: (lessonId: string) => `/student/lessons/${lessonId}/progress`,
    certificates: "/student/certificates",
    claimCertificate: (courseId: string) => `/student/certificates/claim/${courseId}`,
    reviews: "/student/reviews",
    myReviews: "/student/reviews/mine",
  },
  admin: {
    students: "/admin/students",
    student: (id: string) => `/admin/students/${id}`,
    studentEnrollments: (id: string) => `/admin/students/${id}/enrollments`,
    studentPayments: (id: string) => `/admin/students/${id}/payments`,
    studentAvatar: (id: string) => `/admin/students/${id}/avatar`,
    instructors: "/admin/instructors",
    instructor: (id: string) => `/admin/instructors/${id}`,
    instructorAvatar: (id: string) => `/admin/instructors/${id}/avatar`,
    courses: "/admin/courses",
    course: (id: string) => `/admin/courses/${id}`,
    courseImage: (id: string) => `/admin/courses/${id}/image`,
    enrollments: "/admin/enrollments",
    payments: "/admin/payments",
    payment: (id: string) => `/admin/payments/${id}`,
    paymentStatus: (id: string) => `/admin/payments/${id}/status`,
    paymentRefund: (id: string) => `/admin/payments/${id}/refund`,
    paymentReceipt: (id: string) => `/admin/payments/${id}/receipt`,
    certificates: "/admin/certificates",
    revokeCertificate: (id: string) => `/admin/certificates/${id}/revoke`,
    reviews: "/admin/reviews",
    moderateReview: (id: string) => `/admin/reviews/${id}/moderate`,
    blogPosts: "/admin/blog/posts",
    blogPost: (id: string) => `/admin/blog/posts/${id}`,
    publishBlogPost: (id: string) => `/admin/blog/posts/${id}/publish`,
    blogCategories: "/admin/blog/categories",
    blogComments: "/admin/blog/comments",
    moderateBlogComment: (id: string) => `/admin/blog/comments/${id}/moderate`,
    contact: "/admin/contact",
    contactStatus: (id: string) => `/admin/contact/${id}/status`,
  },
};
export default Endpoints;
